require 'rake/clean'
require 'pathname'
require 'yaml'
require 'rake/ext/pathname'
require 'rake/ext/string'

PUBLICATION_SOURCE_DIR = Pathname(ENV['DBP_PUBLICATION_DIR'])
PUBLICATION_SOURCE_FILE = PUBLICATION_SOURCE_DIR / 'publication.yaml'
MANUSCRIPT_SOURCE_DIR = PUBLICATION_SOURCE_DIR / 'manuscript'
MANUSCRIPT_LISTING_SOURCE_FILE = MANUSCRIPT_SOURCE_DIR / 'listing.yaml'

FIXED_DIR = Pathname('_fixed')
FIXED_FILES = FileList[FIXED_DIR / '**/*']

DATA_DIR = Pathname('_data')
MANUSCRIPT_LISTING_FILE = DATA_DIR / 'manuscript.yaml'
PUBLICATION_DATA_FILE = DATA_DIR / 'publication.yaml'

PUBLICATION = YAML.load_file(PUBLICATION_SOURCE_FILE)
CONFIG = YAML.load_file('_config.yaml')

file PUBLICATION_DATA_FILE => PUBLICATION_SOURCE_FILE do |t|
  cp t.source, t.name
end

def copies(from:, to:)
  sources = FileList[from / '**/*'].exclude { |f| Pathname(f).directory? }
  targets = sources.pathmap("%{^#{from}/,#{to}/}p")
  targets.zip(sources).each do |target, source|
    target_dir = target.pathmap('%d')
    directory target_dir
    file target => [source, target_dir] do |t|
      cp t.source, target_dir
    end
  end
  targets
end

MANUSCRIPT_DIR = Pathname('manuscript')
TEX_PATH_TO_MARKDOWN_PATH = "%{^#{MANUSCRIPT_SOURCE_DIR}/,#{MANUSCRIPT_DIR}/}X.md"
MARKDOWN_PATH_TO_TEX_PATH = "%{^#{MANUSCRIPT_DIR}/,#{MANUSCRIPT_SOURCE_DIR}/}X.tex"
MANUSCRIPT_FILES = FileList[MANUSCRIPT_SOURCE_DIR / '**/*.tex'].pathmap(TEX_PATH_TO_MARKDOWN_PATH)
EPUB_PUBLICATION_FILES = copies(from: PUBLICATION_SOURCE_DIR / 'epub', to: '.')

BUILD_DIR = Pathname('_site')
OPF_FILE = BUILD_DIR / 'package.opf'

SOURCE_FILES = FileList.new('**/*') do |l|
  l.exclude { |f| File.directory? f }
  l.exclude /^_out/
  l.exclude /^_site/
  l.exclude(CONFIG['exclude'])
end

# This actually builds all of the content files,
# not only the OPF file.
file OPF_FILE => SOURCE_FILES
file OPF_FILE => MANUSCRIPT_FILES
file OPF_FILE => MANUSCRIPT_LISTING_FILE
file OPF_FILE => EPUB_PUBLICATION_FILES
file OPF_FILE => PUBLICATION_DATA_FILE
file OPF_FILE do
  sh 'jekyll', 'build'
end

EPUB_FILE = Pathname(ENV['DBP_EPUB_FILE'])
OUT_DIR = EPUB_FILE.dirname
directory OUT_DIR
file EPUB_FILE => [OPF_FILE, OUT_DIR] + FIXED_FILES do |t|
  rm_f t.name
  cd(FIXED_DIR) do
    sh 'zip', t.name, '-rX0', 'mimetype'
    sh 'zip', t.name, '-rDX9', '.', '-x', 'mimetype'
  end
  cd(BUILD_DIR) { sh 'zip', t.name, '-rDX9', '.' }
end

file MANUSCRIPT_LISTING_FILE => MANUSCRIPT_LISTING_SOURCE_FILE do |t|
  listing = YAML.load_file(t.source)
  File.open(t.name, 'w') do |f|
    listing.each{|line| f.puts "- manuscript/#{line}.html"}
  end
end

EPUB_CHECK_REPORT = EPUB_FILE.ext('json')
file EPUB_CHECK_REPORT => EPUB_FILE do |t|
  sh 'epubcheck', t.source, '--json', t.name
end

rule '.md' => proc { |f| f.pathmap(MARKDOWN_PATH_TO_TEX_PATH) } do |t|
  dir = t.name.pathmap('%d')
  mkpath dir
  sh 'tex2md', t.source, dir
end

task default: [:all]

desc 'Build and check the epub file (default)'
task all: [:check]

desc 'Build the epub file'
task epub: [EPUB_FILE]

desc 'Check the epub file'
task check: [EPUB_CHECK_REPORT]

CLEAN.include BUILD_DIR
