require 'rake/clean'
require 'rake/ext/pathname'

PDF_FORMAT_FILE = Pathname(ENV['DBP_OUTPUT_FILE'])

desc 'Build the format file'
task default: [:format]

desc 'Build the format file'
task format: [PDF_FORMAT_FILE]

file PDF_FORMAT_FILE => FileList['*.tex'] do
  sh 'pdftex', '-interaction=batchmode', '-etex', '-enc',  '-ini', '-jobname', PDF_FORMAT_FILE.pathmap('%X').to_s, 'dbp'
end

CLEAN.include(PDF_FORMAT_FILE.ext('log'))
CLOBBER.include(PDF_FORMAT_FILE)
