require 'rake/clean'

format_name = 'dbp'

tex_file = "#{format_name}.tex"
format_file = "#{format_name}.fmt"
log_file = "#{format_name}.log"

task default: [:clean, :build, :log]

desc 'Build the format file'
task build: [format_file]

desc 'Show the log file'
task :log do
  print `cat #{log_file}`
end

file format_file do
  `pdftex -interaction=batchmode -etex -enc -ini #{tex_file}`
end

CLEAN << format_file
CLEAN << log_file
