require 'rake/clean'
require 'pathname'

BUILD_DIR = Pathname('_site')
EPUB_DIR = Pathname('_out')
FIXED_DIR = '_fixed'

directory EPUB_DIR

desc 'Build and check standard and kindle epubs'
task default: [:check_standard, :check_kindle ]

desc 'Build standard epub'
task standard_epub: [:standard_content, EPUB_DIR] do
  epub 'standard'
end

desc 'Build kindle epub'
task kindle_epub: [:kindle_content, EPUB_DIR] do
  epub 'kindle'
end

desc 'Check standard epub'
task check_standard: [:standard_epub] do
  check 'standard'
end

desc 'Check kindle epub'
task check_kindle: [:kindle_epub] do
  check 'kindle'
end

desc 'Build kindle content files'
task kindle_content: [] do
  build 'kindle'
end

desc 'Build standard content files'
task standard_content: [] do
  build 'standard'
end

def build(edition)
  sh 'jekyll', 'build', "--destination=#{content_dir(edition)}", "--config=_config.yaml,_#{edition}-edition.yaml"
end

def check(edition)
  sh 'epubcheck', epub_file(edition).to_s
end

def content_dir(edition)
  BUILD_DIR / edition
end

def epub(edition)
  epub_file = epub_file(edition).expand_path.to_s
  rm_f epub_file
  cd(FIXED_DIR) do
    sh 'zip', epub_file, '-rX0', 'mimetype'
    sh 'zip', epub_file, '-rDX9', '.', '-x', 'mimetype', '.DS_Store'
  end
  cd(content_dir(edition)) { sh 'zip', epub_file, '-rDX9', '.', '-x' '.DS_Store' }
end

def epub_file(edition)
  EPUB_DIR / "#{edition}.epub"
end

CLEAN.include BUILD_DIR
CLOBBER.include epub_file('standard'), epub_file('kindle')
