require 'rake/clean'
require 'pathname'

BUILD_DIR = Pathname('_site')
EPUB_DIR = Pathname('_out')
FIXED_DIR = '_fixed'

MOBI_CONFIG_FILE = Pathname('_mobi-edition.yaml')
EPUB_CONFIG_FILE = Pathname('_epub-edition.yaml')

SOURCE_FILES = FileList.new('**/*') do |l|
  l.exclude /^_out/
  l.exclude /^_site/
  l.exclude('Rakefile')
  l.exclude { |f| File.directory? f }
end

EPUB_SOURCE_FILES = SOURCE_FILES.clone.exclude(MOBI_CONFIG_FILE)
MOBI_SOURCE_FILES = SOURCE_FILES.clone.exclude(EPUB_CONFIG_FILE).exclude(/^cover/)

EPUB_BUILD_FILES = EPUB_SOURCE_FILES.clone
                      .exclude(/^_/)
                      .pathmap('_site/epub/%X%{md,html;scss,css}x')

MOBI_BUILD_FILES = MOBI_SOURCE_FILES.clone
                      .exclude(/^_/)
                      .pathmap('_site/mobi/%X%{md,html;scss,css}x')

task :list do
  puts 'Epub build files:'
  EPUB_BUILD_FILES.each { |f| puts "   #{f}"}
end

directory EPUB_DIR

desc 'Build and check epub and mobi'
task default: [:check_epub, :check_mobi ]

desc 'Build epub'
task epub: [:epub_content, EPUB_DIR] do
  epub 'epub'
end

desc 'Build mobi'
task mobi: [:mobi_content, EPUB_DIR] do
  epub 'mobi'
end

desc 'Check epub'
task check_epub: [:epub] do
  check 'epub'
end

desc 'Check mobi epub'
task check_mobi: [:mobi] do
  check 'mobi'
end

desc 'Build mobi content files'
task mobi_content: [] do
  build 'mobi'
end

desc 'Build epub content files'
task epub_content: [] do
  build 'epub'
end

def build(edition)
  sh 'jekyll', 'build', "--destination=#{content_dir(edition)}", "--config=_config.yaml,_#{edition}-edition.yaml"
end

def check(edition)
  sh 'epubcheck', epub_file(edition).to_s
end

def content_dir(edition)
  BUILD_DIR / edition
end

def epub(edition)
  epub_file = epub_file(edition).expand_path.to_s
  rm_f epub_file
  cd(FIXED_DIR) do
    sh 'zip', epub_file, '-rX0', 'mimetype'
    sh 'zip', epub_file, '-rDX9', '.', '-x', 'mimetype', '.DS_Store'
  end
  cd(content_dir(edition)) { sh 'zip', epub_file, '-rDX9', '.', '-x' '.DS_Store' }
end

def epub_file(edition)
  EPUB_DIR / "#{edition}.epub"
end

CLEAN.include BUILD_DIR
CLOBBER.include epub_file('epub'), epub_file('mobi')
