require 'rake/clean'
require 'pathname'

BUILD_DIR = Pathname('_site')
EPUB_DIR = Pathname('_out')
FIXED_DIR = Pathname('_fixed')

EPUB_CONFIG_FILE = Pathname('_epub-edition.yaml')
MOBI_CONFIG_FILE = Pathname('_mobi-edition.yaml')

FIXED_FILES = FileList[FIXED_DIR / '**/*']

SOURCE_FILES = FileList.new('**/*') do |l|
  l.exclude /^_out/
  l.exclude /^_site/
  l.exclude('Rakefile')
  l.exclude { |f| File.directory? f }
end

EPUB_SOURCE_FILES = SOURCE_FILES.clone.exclude(MOBI_CONFIG_FILE)
EPUB_BUILD_DIR = BUILD_DIR / 'epub'
EPUB_BUILD_FILES = EPUB_SOURCE_FILES.clone
                      .exclude(/^_/)
                      .pathmap("#{EPUB_BUILD_DIR}/%X%{md,html;scss,css}x")
EPUB_OPF_BUILD_FILE = EPUB_BUILD_DIR / 'package.opf'
file EPUB_OPF_BUILD_FILE => EPUB_SOURCE_FILES do
  sh 'jekyll', 'build', "--destination=#{EPUB_BUILD_DIR}", "--config=_config.yaml,#{EPUB_CONFIG_FILE}"
end
EPUB_FILE = EPUB_DIR / 'epub.epub'

MOBI_SOURCE_FILES = SOURCE_FILES.clone.exclude(EPUB_CONFIG_FILE).exclude(/^cover/)
MOBI_BUILD_DIR = BUILD_DIR / 'mobi'
MOBI_BUILD_FILES = MOBI_SOURCE_FILES.clone
                      .exclude(/^_/)
                      .pathmap("#{MOBI_BUILD_DIR}/%X%{md,html;scss,css}x")
MOBI_OPF_BUILD_FILE = MOBI_BUILD_DIR / 'package.opf'
file MOBI_OPF_BUILD_FILE => MOBI_SOURCE_FILES do
  sh 'jekyll', 'build', "--destination=#{MOBI_BUILD_DIR}", "--config=_config.yaml,#{MOBI_CONFIG_FILE}"
end
MOBI_FILE = EPUB_DIR / 'mobi.epub'

directory EPUB_DIR

desc 'Build and check epub and mobi'
task default: [ :epub, :mobi ]

desc 'Build and check epub'
task epub: [EPUB_FILE]

desc 'Build amd check mobi'
task mobi: [MOBI_FILE]

file EPUB_FILE => [EPUB_OPF_BUILD_FILE, EPUB_DIR] + FIXED_FILES do |t|
  epub EPUB_FILE, EPUB_BUILD_DIR
  sh 'epubcheck', t.name
end

file MOBI_FILE => [MOBI_OPF_BUILD_FILE, EPUB_DIR] + FIXED_FILES do |t|
  epub MOBI_FILE, MOBI_BUILD_DIR
  sh 'epubcheck', t.name
end

def epub(fname, content_dir)
  full_name = fname.expand_path.to_s
  rm_f full_name
  cd(FIXED_DIR) do
    sh 'zip', full_name, '-rX0', 'mimetype'
    sh 'zip', full_name, '-rDX9', '.', '-x', 'mimetype'
  end
  cd(content_dir) { sh 'zip', full_name, '-rDX9', '.' }
end

CLEAN.include BUILD_DIR
CLOBBER.include EPUB_DIR
