require 'rake/clean'

format_name = 'dbp'

format_file = "#{format_name}.fmt"
log_file = "#{format_name}.log"

desc 'Build the format file'
task default: [:format]

desc 'Build the format file'
task format: [format_file]

file format_file => FileList['*.tex'] do
  sh 'pdftex', '-interaction=batchmode', '-etex', '-enc',  '-ini', format_name
end

CLEAN << log_file
CLOBBER << format_file
