require 'rake/clean'
require 'pathname'
require 'yaml'
require 'rake/ext/pathname'
require 'rake/ext/string'

PUBLICATION_SOURCE_DIR = Pathname(ENV['DBP_PUBLICATION_DIR'])
PUBLICATION_SOURCE_FILE = PUBLICATION_SOURCE_DIR / 'publication.yaml'
MANUSCRIPT_SOURCE_DIR = PUBLICATION_SOURCE_DIR / 'manuscript'
MANUSCRIPT_LISTING_SOURCE_FILE = MANUSCRIPT_SOURCE_DIR / 'listing.yaml'

FIXED_DIR = Pathname('_fixed')
FIXED_FILES = FileList[FIXED_DIR / '**/*']

DATA_DIR = Pathname('_data')
MANUSCRIPT_LISTING_FILE = DATA_DIR / 'manuscript.yaml'
PUBLICATION_DATA_FILE = DATA_DIR / 'publication.yaml'

PUBLICATION = YAML.load_file(PUBLICATION_SOURCE_FILE)
CONFIG = YAML.load_file('_config.yaml')

file PUBLICATION_DATA_FILE => PUBLICATION_SOURCE_FILE do |t|
  cp t.source, t.name
end

MANUSCRIPT_DIR = Pathname('manuscript')
MARKDOWN_PATH = "%{^#{MANUSCRIPT_SOURCE_DIR}/,#{MANUSCRIPT_DIR}/}X.md"
EPUB_PUBLICATION_FILES = files_copied(from: PUBLICATION_SOURCE_DIR / 'epub', to: '.')

MANUSCRIPT_FILES = files_created(from_each: MANUSCRIPT_SOURCE_DIR / '**/*.tex', as: MARKDOWN_PATH) do |dep|
  sh 'tex2md', dep[:source], dep[:dir]
end

BUILD_DIR = Pathname('_site')
OPF_FILE = BUILD_DIR / 'package.opf'

SOURCE_FILES = FileList.new('**/*') do |l|
  l.exclude { |f| File.directory? f }
  l.exclude /^_out/
  l.exclude /^_site/
  l.exclude(CONFIG['exclude'])
end

# This actually builds all of the content files,
# not only the OPF file.
file OPF_FILE => SOURCE_FILES
file OPF_FILE => MANUSCRIPT_FILES
file OPF_FILE => MANUSCRIPT_LISTING_FILE
file OPF_FILE => EPUB_PUBLICATION_FILES
file OPF_FILE => PUBLICATION_DATA_FILE
file OPF_FILE do
  sh 'jekyll', 'build'
end

EPUB_FILE = Pathname(ENV['DBP_OUTPUT_FILE'])
OUT_DIR = EPUB_FILE.dirname
directory OUT_DIR
file EPUB_FILE => [OPF_FILE, OUT_DIR] + FIXED_FILES do |t|
  rm_f t.name
  cd(FIXED_DIR) do
    sh 'zip', t.name, '-rX0', 'mimetype'
    sh 'zip', t.name, '-rDX9', '.', '-x', 'mimetype'
  end
  cd(BUILD_DIR) { sh 'zip', t.name, '-rDX9', '.' }
end

file MANUSCRIPT_LISTING_FILE => MANUSCRIPT_LISTING_SOURCE_FILE do |t|
  listing = YAML.load_file(t.source)
  File.open(t.name, 'w') do |f|
    listing.each{|line| f.puts "- manuscript/#{line}.html"}
  end
end

EPUB_CHECK_REPORT = EPUB_FILE.ext('json')
file EPUB_CHECK_REPORT => EPUB_FILE do |t|
  sh 'epubcheck', t.source, '--json', t.name
end

task default: [:all]

desc 'Build and check the epub file (default)'
task all: [:check]

desc 'Build the epub file'
task epub: [EPUB_FILE]

desc 'Check the epub file'
task check: [EPUB_CHECK_REPORT]

CLEAN.include BUILD_DIR
