require 'rake/clean'
require 'pathname'
require 'rake/ext/pathname'

PDF_FILE = Pathname(ENV['DBP_PDF_FILE'] || 'book.pdf')
OUT_DIR = PDF_FILE.dirname

directory OUT_DIR

fmt_name = 'format/dbp'
fmt_file = "#{fmt_name}.fmt"

desc 'Typeset the book as a PDF file'
task default: [:pdf]

desc 'Typeset the book as a PDF file'
task pdf: [PDF_FILE]

file PDF_FILE => [OUT_DIR] do |t|
  sh 'pdftex', '-interaction=batchmode', '-fmt', fmt_name, '-jobname', t.name.pathmap('%X'), 'book'
end
file PDF_FILE => FileList['*.tex', 'author/*.tex', 'manuscript/*.tex', 'preview/*.tex']
file PDF_FILE => [fmt_file]

CLOBBER.include(PDF_FILE, PDF_FILE.ext('log'))
