require 'rake/clean'
require 'pathname'

slug = 'book'

pdf_file = "#{slug}.pdf"
log_file = "#{slug}.log"
fmt_name = 'format/dbp'
fmt_file = "#{fmt_name}.fmt"

desc 'Typeset the book as a PDF file'
task default: [:pdf]

desc 'Typeset the book as a PDF file'
task pdf: [pdf_file]

file pdf_file do
  sh 'pdftex', '-interaction=batchmode', '-fmt', fmt_name, slug
end
file pdf_file => FileList['*.tex', 'author/*.tex', 'manuscript/*.tex', 'preview/*.tex']
file pdf_file => [fmt_file]

CLEAN.include(log_file)
CLOBBER.include(pdf_file)
