require 'rake/clean'
require 'pathname'
require 'yaml'
require 'rake/ext/pathname'

TEMPLATE_DIR = Pathname(__FILE__).dirname
UTILS = TEMPLATE_DIR / 'utils'

require UTILS

BOOK_DIR = Pathname(ENV.fetch('DBP_BOOK_DIR', Pathname.pwd)).expand_path
PUBLICATION_DIR = BOOK_DIR / 'publication'
PUBLICATION_DATA_FILE = PUBLICATION_DIR / 'publication.yaml'

PUBLICATION = YAML.load_file(PUBLICATION_DATA_FILE)
SLUG = PUBLICATION['slug']

DBP_BUILD_DIR = Pathname('/var/tmp/dbp')
BOOK_BUILD_DIR = DBP_BUILD_DIR + SLUG

OUT_DIR = BOOK_DIR / 'uploads'

def output_file(medium)
  (OUT_DIR / SLUG).ext(medium.to_s)
end

def produce(medium:, deps: [], env: {})
  medium = medium.to_s
  template_dir = TEMPLATE_DIR / medium
  build_dir = BOOK_BUILD_DIR / template_dir.basename
  output_file = output_file(medium)
  rake_env = env.merge(DBP_PUBLICATION_DIR: PUBLICATION_DIR, DBP_OUTPUT_FILE: output_file)

  file output_file => copies(from: template_dir, to: build_dir)
  file output_file => FileList[PUBLICATION_DIR / medium / '**/*']
  file output_file => FileList[PUBLICATION_DIR / 'manuscript' / '**/*']
  file output_file => PUBLICATION_DATA_FILE
  file output_file => deps

  desc "Build the #{medium} file"
  task medium do |t|
    cd(build_dir) { rake rake_env }
  end

  task medium => output_file
  task all: medium
end

PDF_FORMAT_TEMPLATE_DIR = TEMPLATE_DIR / 'pdf-format'
PDF_FORMAT_BUILD_DIR = BOOK_BUILD_DIR / PDF_FORMAT_TEMPLATE_DIR.basename
PDF_FORMAT_TEMPLATE_FILES = copies(from: PDF_FORMAT_TEMPLATE_DIR, to: PDF_FORMAT_BUILD_DIR)
PDF_FORMAT_FILE = (BOOK_BUILD_DIR / 'dbp.fmt').expand_path

directory PDF_FORMAT_BUILD_DIR
file PDF_FORMAT_FILE => PDF_FORMAT_TEMPLATE_FILES + [PDF_FORMAT_BUILD_DIR] do |t|
  cd(PDF_FORMAT_BUILD_DIR) { rake DBP_PDF_FORMAT_FILE: t.name }
end

produce(medium: :pdf, deps: PDF_FORMAT_FILE, env: { DBP_PDF_FORMAT_FILE: PDF_FORMAT_FILE })
produce(medium: :epub)

MOBI_FILE = output_file(:mobi)
file MOBI_FILE => output_file(:epub) do |t|
  sh 'kindlegen', t.source
end

task default: :all

desc 'Build all formats'
task all: [:mobi]

desc 'Build the mobi file'
task mobi: MOBI_FILE

def rake(env = {})
  env_args = env.map { |k,v| "#{k}=#{v}" }
  sh 'rake', '-r', UTILS.to_s, *env_args
end

CLEAN.include BOOK_BUILD_DIR
CLOBBER.include OUT_DIR
